#!/bin/bash

# Testing a single long sequence (KITTI/VIPER)
python deepvo/main.py sequencetest \
--input xyz_all_seq_KITTI_dropout_grow_sequence \
--output xyz_all_seq_KITTI_dropout_grow_sequence/long_sequence_10 \
--test \
--cuda \
--sequence 100 \
--hidden 1000 \
--layers 2 \
--workers 12 \
--print_freq 1 \
--max_size 0 0 0 \
--dataset KITTI \
--sequence_name 10 \
#--checkpoint checkpoint-epoch-086.pth.tar \