# Adam, no adjust lr, custon cnn (dilation), dot product rotation loss + L2 for translation loss
# Single image (not pairwise)
# Looping
# Training

module load anaconda

CUDA_VISIBLE_DEVICES=0 \
python per_pixel_lstm_teacher/main.py pose7D \
--output gpu00_04_per_pixel_lstm \
--train \
--cuda \
--epochs 100 \
--sequence 15 \
--hidden 100 \
--layers 5 \
--lr 0.004 \
--beta 0.1 \
--workers 4 \
--print_freq 1 \
#--max_size 100 30 30 \
