#!/bin/bash

# Testing a single long sequence (KITTI/VIPER)
python deepvo_inc/main.py sequencetest \
--input xyz_all_seq_short_incremental_dropout \
--output xyz_all_seq_short_incremental_dropout/long_sequence_011_on_VIPER \
--test \
--cuda \
--sequence 100 \
--hidden 1000 \
--layers 2 \
--workers 12 \
--print_freq 1 \
--max_size 0 0 0 \
--dataset VIPER \
--sequence_name 011 \
--checkpoint checkpoint-epoch-043.pth.tar \