#!/bin/bash

# Testing a single long sequence (KITTI/VIPER)
python deepvo_inc_no_lstm/main.py sequencetest \
--input xyz_all_seq_short_incremental_dropout_nolstm \
--output xyz_all_seq_short_incremental_dropout_nolstm/long_sequence_05_on_KITTI \
--test \
--cuda \
--sequence 100 \
--hidden 1000 \
--layers 2 \
--workers 12 \
--print_freq 1 \
--max_size 0 0 0 \
--dataset KITTI \
--sequence_name 05 \
#--checkpoint checkpoint-epoch-043.pth.tar \