#!/bin/bash

#$ -N train_imagenet_pose
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1

# Array job: -t <range>
#$ -t 1

#$ -l h=node01

#$ -v DISPLAY

module load anaconda

# Training
python main.py binarypose --cuda --name imagenetpose3 --train --epochs 50 --angle 40 --zplane 0.7 --batch_size 10 --lr 0.01 --workers 4 --print_freq 50 --max_size 8000

# Testing
python main.py binarypose --cuda --name imagenetpose3 --test --angle 40 --zplane 0.7 --batch_size 10 --workers 4