#!/bin/bash

#$ -N download_files
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1

# Array job: -t <range>
#$ -t 1

#$ -l h=node01

#$ -v DISPLAY

mkdir -p ~/data/Cambridge/KingsCollege
wget -O ~/data/Cambridge/KingsCollege/dataset.zip "https://www.repository.cam.ac.uk/bitstream/handle/1810/251342/KingsCollege.zip?sequence=4&isAllowed=y"
unzip ~/data/Cambridge/KingsCollege/dataset.zip -d ~/data/Cambridge/KingsCollege


