#!/bin/bash

#$ -N train_gta5
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1

# Array job: -t <range>
#$ -t 1

#$ -l h=node01

#$ -v DISPLAY

module load anaconda

# Training
python full-pose/main.py pose7D \
--name gta5pose7D \
--cuda \
--train \
--epochs 20 \
--sequence 20 \
--lr 0.0001 \
--workers 4 \
--print_freq 1 \
--max_size 1000 200 0

# Testing
python full-pose/main.py pose7D \
--name gta5pose7D \
--cuda \
--test \
--sequence 25 \
--workers 4 \
--print_freq 1 \
--max_size 0 0 1000
