# Adam, no adjust lr, L2 loss for rotation only, LSTM only with generated point cloud features
# Training

module load anaconda

CUDA_VISIBLE_DEVICES=2 \
python point_cloud/main.py multiclass1Dtranslation \
--output gpu2_temp \
--train \
--cuda \
--epochs 50 \
--sequence 100 \
--keypoints 16 \
--features 1 \
--hidden 100 \
--layers 4 \
--lr 0.0001 \
--workers 4 \
--print_freq 1 \
--max_size 100 10 10 \
