# Adam, no adjust lr, L2 loss for rotation only, LSTM only with generated point cloud features
# Training

module load anaconda

CUDA_VISIBLE_DEVICES=2 \
python point_cloud/main.py pose7D \
--output gpu02_00_point_cloud_two_points_left_right_lr=0.001_points=16 \
--train \
--cuda \
--epochs 10 \
--sequence 2 \
--keypoints 16 \
--hidden 1000 \
--layers 2 \
--lr 0.001 \
--beta 0.1 \
--workers 4 \
--print_freq 1 \
--max_size 10000 100 100 \
