# Adam, no adjust lr, custon cnn (dilation), dot product rotation loss + L2 for translation loss
# Single image (not pairwise)
# Looping
# Training

module load anaconda

CUDA_VISIBLE_DEVICES=1 \
python point_cloud/main.py pose7D \
--output gpu01_04_point_cloud \
--train \
--cuda \
--epochs 100 \
--sequence 15 \
--hidden 100 \
--layers 5 \
--lr 0.004 \
--beta 0.1 \
--workers 4 \
--print_freq 1 \
--max_size 100 30 30 \
