# Adam, no adjust lr, L2 loss for rotation only, LSTM only with generated point cloud features
# Training

module load anaconda


python point_cloud/main.py pose7D \
--output gpu01_00_point_cloud_two_points_left_right_lr=0.001_points=8 \
--train \
--cuda \
--epochs 10 \
--sequence 1000 \
--keypoints 10 \
--hidden 100 \
--layers 1 \
--lr 0.001 \
--beta 0.1 \
--workers 4 \
--print_freq 1 \
--max_size 10 10 2 \
