# Adam, no adjust lr, custon cnn (dilation), dot product rotation loss + L2 for translation loss
# Single image (not pairwise)
# Looping
# Training

module load anaconda

CUDA_VISIBLE_DEVICES=0 \
python point_cloud/main.py pose7D \
--output gpu00_00_point_cloud \
--train \
--cuda \
--epochs 100 \
--sequence 2 \
--keypoints 2 \
--hidden 1000 \
--layers 2 \
--lr 0.001 \
--beta 0.1 \
--workers 4 \
--print_freq 1 \
--max_size 1000 100 100 \
